Merge MintMaker and MPP-Renovate images
konflux-ci/mintmaker-renovate-image pull request #52
Opened 2024-08-28 21:04 UTC by FernandesMF

We have been maintaining two different images, one for our runners in MPP, and another for Konflux. This commit merges the two images, which can now be used in both environments and will reduce our maintenance efforts (hopefully).

The most important changes with respect to the MPP image are:
- this image is based on ubi9-minimal (the MPP image was based on fedora)
- this image lacks python 3.8/3.10, as ubi9 does not have packages for these versions
- this image does not correction to rh-ca bundle mount

The moist important changes with respect to the previous version are:
- drop installation of `npm` and `nodejs` packages via the package manager
- manual installation of `nodejs`

There will be a follow-up change in the MPP deployment files. This change must be merged first.

JIRA: [CWFHEALTH-3276]

### Testing remarks
I made dry runs in the both MPP and Konflux stage environments. The image worked fine in both.

A few minor remarks:
  - MPP: there was a lookup error with a go package (kubevirt.io/api); this seems to be unrelated to the image itself
  - STN: there was an authentication error due to revoked token, but this error was already present before the current image changes; since the image worked fine in MPP for the same authentication, this is not related tothe image itself

2024-08-29 05:54 UTC, staticf0x requested changes

2024-08-29 05:54 UTC, staticf0x commented on Dockerfile
>      microdnf install -y \
```suggestion
RUN microdnf update -y && \
    microdnf install -y \
```

2024-08-29 05:54 UTC, staticf0x commented on Dockerfile
> +ARG NODEJS_VERSION=20.17.0
```suggestion
ARG RENOVATE_VERSION=38.55.2-rpm

# NodeJS version used for Renovate, has to satisfy the version
# specified in Renovate's package.json
ARG NODEJS_VERSION=20.17.0
```

I'd just put this comment here to warn against just updating this randomly :smile:

2024-08-29 05:54 UTC, staticf0x commented on Dockerfile
> +        podman \
```suggestion
```

I think we can drop podman, it was required before skopeo became the go-to thing.

2024-08-29 06:22 UTC, qixiang commented on Dockerfile
> +    rm -r node-v${NODEJS_VERSION}-linux-x64.tar.xz
```suggestion
    rm -fr node-v${NODEJS_VERSION}-linux-x64 && \
    rm -f node-v${NODEJS_VERSION}-linux-x64.tar.xz
```

2024-08-29 06:23 UTC, qixiang commented on Dockerfile
> +
```suggestion
```

2024-08-29 14:42 UTC, FernandesMF commented
Hey team, thank you for the reviews! I applied the suggestions and squashed the changes in a single commit.
Could you have a second look?

2024-08-30 08:36 UTC, staticf0x approved these changes
LGTM

2024-08-30 14:27 UTC, merged